name = "NoGood Theme"
license = "MIT"
licenselink = "https://github.com/budparr/gohugo-theme-ananke/blob/master/LICENSE.md"

description = "A Base theme for building full featured Hugo sites"
homepage = "https://soundcloud.com/no_good_music"
tags = ["Music", "Electronica", "Producer", "EDM", "Pop", "AudioApostlesCollective"]
features = ["posts", "shortcodes", "related content", "comments"]

[author]
  name = "socHACKi"
  homepage = "https://github.com/jsochacki"

