baseURL = "https://audioapostlerecords.com"
languageCode = "en-us"
title = "No Good Music"
theme = "ananke"

disqusShortname = 'NoGood'

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 6 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  description = "The last theme you'll ever need. Maybe."
  facebook = "https://www.facebook.com/AudioApostles/"
  twitter = "https://twitter.com/AudioApostles"
  instagram = "https://www.instagram.com/audioapostles/"
  youtube = "https://www.youtube.com/channel/UCnvR5iIEkij2pHVrDbDjMPg"
  github = ""
  linkedin = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  #background_color_class = "bg-black"
  featured_image = "/images/LNoGood.jpg"
  recent_posts_number = 2
